# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_SQLFormatteR_wrappers", use_symbols = TRUE, package_name = "SQLFormatteR")

#' @usage NULL
#' @useDynLib SQLFormatteR, .registration = TRUE
NULL

#' Formats whitespace in a SQL string to make it easier to read.
#' Optionally replaces parameter placeholders with `params`.
#' @noRd
#' @keywords internal
sql_format_wrapper <- function(query, options) .Call(wrap__sql_format_wrapper, query, options)


# nolint end
